### ISSUE TITLE
Support timeouts in retry and retryAsync

### ISSUE THREAD

**Issue by extesy** [zmanio/atmos#7]
I'd really like to have atmos support for timeouts, especially in async mode, ideally without using akka, just with timer.

**Comment by lpryor** [comment]
Atmos does support timeouts to some extent, although they might more appropriately be called deadlines. You can use them by specifying a duration when creating a termination policy:

```
val retryPolicy = retryFor { 10 seconds }
```

... although this will only make sure that no more retry attempts are made after the specified duration has elapsed. It will NOT interrupt an attempt while it is still running. So using the retry policy above with a function that blocked for 30 seconds would cause the entire retry operation to take 30 seconds to complete, not 10.

In the async scenario we're limited by what can be done with Scala Futures. While there is no way to force the async task associated with a Future to terminate, you can work around this a bit by wrapping a normal Future with a custom future that can time out and produce a Failure before the original future actually completes (some good options for implementing this are listed here: http://semberal.github.io/scala-future-timeout-patterns.html). Using a theoretical TimeoutFuture would allow you do do a couple different things:

 - Wrapping your retry function in a TimeoutFuture would put a limit on how long each attempt was allowed to execute: `retryAsync() { TimeoutFuture(300 millis) { tryToDoSomething() } }` would limit each attempt to 300 milliseconds before retrying.

 - Wrapping your entire retry operation in a TimeoutFuture would limit the amount of time that all retry attempts could take: `TimeoutFuture(30 seconds) { retryAsync() { tryToDoSomething() } }` would limit the entire operation to 30 seconds but each attempt could take as long as it likes.

It's feasible that atmos could implement something like TimeoutFuture under the covers, but the real problems start when trying to bring hard timeouts into the realm of synchronous retries.

In the case of synchronous retries we can't just let the retry attempt continue in the background while we claim that it's timed out like we do for asynchronous. Instead, we have to actually stop the thread that's executing the retry attempt and make it return to the caller. This starts to get pretty to close to cancellation as opposed to timing out, and cancellation is outside the scope of atmos.

If you have ideas about how this would work that I'm not thinking of I'd love to hear them, but at this time I don't see a viable path toward supporting anything but the current soft timeout behavior without edging into topics like cancellation or dedicated thread management, which do not directly work towards the goal of "simplifying the retry loop."

**Comment by extesy** [comment]
Thank you for a very detailed response! Synchronous retry seems to be much harder to do than async and I agree that it will probably require some application logic anyways. How about retryAsync? I like TimeoutFuture idea, can it be supported natively by atmos as some kind of TimeoutPolicy?

**Comment by lpryor** [comment]
So I've taken a look at this feature and I'm still of the opinion that adding a hard deadline to the `RetryPolicy` structure is not something I want to do. My main objection is that adding something to the policy that only works for asynchronous retries will be misleading and/or confusing for users of the synchronous path. Take this as an example:
```scala
import atmos.dsl._
import scala.concurrent.duration._

 // The theoretical timeoutAfter method applies a hard timeout to the policy.
implicit val retryPolicy = retryFor { 5 attempts } timeoutAfter { 30 seconds }

retry() { doSomethingThatTakesFiveMinutes() }
```
Looking at the above code, one would think that the retry operation would take at most 30 seconds. In reality, seeing as there is no way to interrupt the execution of `doSomethingThatTakesFiveMinutes()`, the operation will take five minutes or more to complete.

On the other hand, I do think this feature is valuable... particularly when using asynchronous retries. In order to address this I've implemented the previously-theorized `TimeoutFuture` and added it's functionality to the atmos DSL.

Atmos uses another library for implementing non-retry-specific behavior: [rummage](https://github.com/zmanio/rummage). Previously atmos was only using the utilities in rummage to support non-blocking asynchronous backoff in asynchronous retries. For this feature I created [`rummage.Deadline`](https://github.com/zmanio/rummage/blob/master/src/main/scala/rummage/deadlines.scala) which is pretty much identical to what I sketched out for `TimeoutFuture` above. You use it like so:
```scala
import rummage.Deadline
import scala.concurrent.duration._
import scala.concurrent.Future

val futureWithDeadline: Future[String] = Deadline(30 seconds) { Future { loadSomeText() } }
```
The `futureWithDeadline` value above will complete with the result of `loadSomeText()` or with a `rummage.DeadlineException` if `loadSomeText()` does not complete within 30 seconds.

You can use `Deadline` in an asynchronous retry operation just like the theoretical `TimeoutFuture` in my previous comment. However, that's not very pretty and runs against the grain of the literate programming style that atmos advocates. So rummage includes a simple deadline DSL that atmos then re-publishes as part of its DSL. The DSL extends `Future` and adds a `withDeadline(Duration)` method that simply wraps a future with a deadline like above:
```scala
import atmos.dsl._
import scala.concurrent.duration._
import scala.concurrent.Future

implicit val retryPolicy = retryFor { 5 attempts }

// Place a deadline on each attempt in a retry operation.
val futureWithAttemptDeadline = retryAsync() { Future { loadSomeText() } withDeadline 30.seconds }

// Place a deadline on the entire retry operation.
val futureWithOperationDeadline = retryAsync() { Future { loadSomeText() } } withDeadline 30.seconds
```

This addition, I hope, satisfies the underlying feature request while keeping your code concise and not disturbing the `retry`/`retryAsync` duality. The deadline feature is available in rummage 1.3 which has been published to Maven central. Deadline DSL support in atmos has been added to the [2.1 development branch](https://github.com/zmanio/atmos/tree/v2.x) and should be released Real Soon Now<sup>tm</sup> (only need to finish test cases for one last feature).

Let me know if this addition satisfies your requirements.

**Comment by extesy** [comment]
Thank you for adding deadlines support! It makes adding timeouts to futures much more convenient. Are you still going to add `timeoutAfter` support to retry policy? I don't see it yet in https://github.com/zmanio/atmos/tree/v2.x branch. While appending deadline to a future solves my use case (thanks, again!), I think the code will look nicer if this timeout was part of the policy, not the future.

**Comment by lpryor** [comment]
The `timeoutAfter` method above does not exist, I only mentioned it as a way to show how it could confuse the situation with synchronous retries.

One of the primary design goals of atmos was to achieve a parity between the synchronous and asynchronous execution models. Users should be able to reason about retries the same way regardless of how their application's threading model works. While I agree that deadline support in the policy would be a better overall solution, I cannot think of a way to support it without disenfranchising the synchronous side of the equation and creating confusion around the context in which certain retry policies can be used.

If you have any ideas about how this could be done while continuing to support arbitrary threading models then know that pull requests are always appreciated! Until such an idea appears, however, the `RetryPolicy` will continue to operate the same in any threading context... which means no hard deadlines at the policy level.

**Comment by lpryor** [comment]
With the release of version 2.1 I'm closing this issue and considering it resolved for the asynchronous case and wontfix for the synchronous case. Thanks again for your feedback!
